
services:
  webserver:
    image: nginx:latest
    container_name: TarotQuiz_webserver_nginx
    volumes:
      - ./docs:/usr/share/nginx/html:ro  # Mount docs folder to Nginx's html directory
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config file
    ports:
      - "8080:80"   # Expose port 8080 on your host, mapped to port 80 inside the container
    restart: unless-stopped
